#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Show last commit info in the repository.
-v		Include a list of changed files.
--grep regexp   Limit the commits to ones with log message that matches the
		specified pattern.
--author regexp	Limit to commits by author.
--no-merge	Exclude any commits that mention merge in the revision summary.
--no-color	Turn off color highlighting.
Usage: "$(basename "$1")" [--no-merge] [-v|--verbose] [--grep regexp] [--author regexp] [--no-color] [PATH...] [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

eval lastArg=\${$#}
repositoryUrl=
if [ "${lastArg#http}" = "$lastArg" ]; then
    repositoryUrl=$(svn-url) || exit $?
fi

svn-wrapper log --limit 1 "$@" "$repositoryUrl"
