#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Show who created / renamed the passed file.
Usage: "$(basename "$1")" PATH [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac
if [ $# -ne 1 ]; then
    echo >&2 "ERROR: Must pass working copy PATH."
    exit 2
fi
serverFilespec=$(svn-pathname --server "$1") || exit $?


logRevision()
{
    svn-wrapper log -c "$1"
}

processRevision()
{
    IFS=' ' read -r revision copyFromPath < <(printf '%s\n' "$1" | \
	xmlstarlet sel --text -t \
	    -m '//logentry' -i ".//path[@action='A'] = '$serverFilespec'" -v "concat(@revision, ' ', .//path/@copyfrom-path)" \
	    -n)

    if [ "$revision" ]; then
	if [ "$copyFromPath" ]; then
	    source=$copyFromPath
	    destination=$serverFilespec
	    serverFilespec=$copyFromPath

	    if type -P commonpath >/dev/null; then
		commonPath=$(commonpath "$source" "$destination")
		source=${source#${commonPath}/}
		destination=${destination#${commonPath}/}
	    fi

	    printf 'Copy from %s to %s\n' "$source" "$destination"
	fi

	logRevision "$revision"
    fi
}


revisionLog=
cat /tmp/svnxml | (read -r line; read -r line; while IFS=$'\n' read -r line
do
    revisionLog="${revisionLog}${revisionLog:+
}$line"
    case "$line" in
	'</logentry>')
	    processRevision "$revisionLog"
	    revisionLog=
	    ;;
    esac
done)
