#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Show statistics on how many lines were last committed by which author.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[-r N[:M]] [-g|--use-merge-history] TARGET[@REV] [-?|-h|--help]'
}

case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

set -o pipefail
svn blame --non-interactive "$@" | cut -d' ' -f 3 | sort | uniq -c | sort -r
