#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Minimal one-line log messages with commit summary. 
--no-merge	Exclude any commits that mention merge in the revision summary. 
--no-color	Turn off color highlighting. 
--server	Instead of local history, only list server revisions that you
		don't have yet. 
Note: svn log option -v is not supported here, but also doesn't make sense here. 
Usage: "$(basename "$1")" [--no-merge] [-c M | -r N[:M]] [-l|--limit ARG] [--no-color] [--server|PATH...] [-?|-h|--help]
HELPTEXT
}

: ${SVN_MERGE_COMMENT_PATTERN:=merg\\(e\\|ed\\|es\\|ing\\|eback\\)\\b}
: ${COLOR_REVISION:='[36m'}
: ${COLOR_RESET:='[0m'}
colorize()
{
    if [ "$isNoColor" ]; then
	cat
    else
	sed --unbuffered -e "s/^\\([^ ]\+\\) \\(.*\\)/${COLOR_REVISION}\\1${COLOR_RESET} \\2/"
    fi
}

typeset filter=cat
typeset isNoColor=
typeset isServerRevisions=
typeset -a allargs=()
while [ $# -gt 0 ]
do
    case "$1" in
	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
	--no-merge)	shift; filter="grep --line-buffered -iv ${SVN_MERGE_COMMENT_PATTERN}";;
	--no-color)	shift; isNoColor='true';;
	--server)	shift; isServerRevisions='true';;
	*)
	    allargs+=("$1")
	    shift
	    ;;
    esac
done
if [ "$isServerRevisions" ]; then
    allargs+=($(svn-serverrevs))
fi

svn log --non-interactive "${allargs[@]}" | sed --unbuffered -ne '
/^r[0-9]\+/{
    s/\(^r[0-9]\+\) *.*/\1 /
    N
    N
    s/\n//g
    p
}
' | $filter | colorize | less --RAW-CONTROL-CHARS
