#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
Remove svn:mergeinfo property from files below the current / passed repository's
root that (wrongly) have such.
Usage: "$(basename "$1")" [PATH] [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

svn-mergeinfo-find "$@" | xargs svn propdel svn:mergeinfo
