#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Show logs and diff of changes to svn:mergeinfo on passed PATH.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[--grep REGEXP [--grep ...]] [-i|--regexp-ignore-case] [--author REGEXP] [-l|--limit ARG] [--no-color] PATH [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac
[ $# -eq 0 ] && { echo >&2 "ERROR: Must pass PATH."; exit 2; }

exec svn-lc --non-recursive --prop only --prop-scope minimal --prop-filter 'svn:mergeinfo' "$@"
