#!/bin/bash

if [[ $# -eq 0 || "${!#}" = -* ]]; then
    svn status "$@"
else
    set -o pipefail

    TMPFILE=$(mktemp --tmpdir "$(basename -- "$0")-XXXXXX" 2>/dev/null || echo "${TEMP:-/tmp}/$(basename -- "$0").$$")
    cleanup()
    {
	rm -f "$TMPFILE" 2>/dev/null
    }
    [ "$DEBUG" ] || trap 'cleanup' EXIT

    svn status "$@" | tee "$TMPFILE" || exit $?

    if [ ! -s "$TMPFILE" ]; then
	# Support extended "svn-status PATTERN" variant. But first ensure that
	# the last argument is not a PATH, and the CWD indeed is a Subversion
	# working copy.
	svn info "${@:1:$(($#-1))}" >/dev/null 2>&1 || exit 0
	searchArg=${!#}
	svn status "${@:1:$(($#-1))}" | GREP_OPTIONS= grep -i "$searchArg"
    fi
fi
