#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Show the revision for the current repo.
Usage: "$(basename "$1")"
HELPTEXT
}

case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

set -o pipefail

modifiedFiles=$(svn status --non-interactive -q "$@")
[ "$modifiedFiles" ] && dirty='-dirty' || dirty=
revision=$(svn info --non-interactive "$@" | sed -n -e 's/^Revision: \(.*\)$/\1/p') || exit $?
printf 'r%s%s\n' "$revision" "$dirty"
