#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Display the word-based differences between two revisions or paths.
Highlights deletions/additions in red/green.
--no-color	Turn off colored diff.
The following 'wdiff' options can be passed:
-s, --statistics
In case the 'dwdiff' command is installed, the following options can be passed:
-d <delimiters>, --delimiters=<delimiters>
-P, --punctuation
-L[<width>], --line-numbers[=<width>]
-C<num>, --context=<num>
-m<num>, --match-context=<num>
--aggregate-changes
-A <algorithm>, --algorithm=<algorithm>
-S[<marker>], --paragraph-separator[=<marker>]

Default is working copy to last commit; use
-r PREV to diff working copy with previous commit and
-r PREV:COMMITTED (or svn dp) to show change in previous commit, and
-r REV:COMMITTED to show changes across revisions.

HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[-b] [-w] [--context] [-c M | -r N[:M]] [--stat|--numstat|--shortstat] [--no-color] [TARGET[@REV]...] [-?|-h|--help]'
}

diffCommand=
diffType=-u
diffOptions=
diffStatArgs=

# Highlight diff output if available.
hasColorDiff=
type -t colordiff >/dev/null && hasColorDiff=t

typeset -a allargs=()
# Simplify setting common diff options (that do not overlap with svn options).
while [ $# -gt 0 ]
do
    case "$1" in
	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
	-b)
	    shift
	    diffOptions="${diffOptions}${diffOptions:+ }-b"
	    ;;
	-w)
	    shift
	    diffOptions="${diffOptions}${diffOptions:+ }-w"
	    ;;
	--context)
	    shift
	    diffCommand="--diff-cmd diff"	# Need to specify an external diff program; the one built into Subversion can only do unified diffs.
	    diffType="-c"
	    ;;
	# Note: --ignore-eol-style seems to be handled internally by svn; it is
	# not supported by GNU diff or colordiff.
	--stat)
	    shift
	    diffStatArgs='-C'
	    ;;
	--numstat)
	    shift
	    diffStatArgs='-C -f0'
	    ;;
	--shortstat)
	    shift
	    diffStatArgs='-C -s'
	    ;;
	--no-color)
	    shift
	    hasColorDiff=
	    ;;
	*)
	    allargs+=("$1")
	    shift
	    ;;
    esac
done
# Note: diffOptions can be passed as a single argument "-x -u -b" as well as the
# two-arg -x "-u -b", but not as individual arguments.
# Note: Must not pass an empty "" argument to svn, or the filtering for TARGET
# doesn't work any more.
set -o pipefail
[ "$diffCommand" -o "$diffOptions" ] && svnDiffOptions="${diffCommand}${diffCommand:+ }-x \"${diffType}${diffOptions:+ }${diffOptions}\""
####D echo svn diff --non-interactive $svnDiffOptions "${allargs[@]}"
if [ "$diffStatArgs" ]; then
    [ "$hasColorDiff" ] || diffStatArgs="${diffStatArgs//-C/}"
    eval svn diff --non-interactive $svnDiffOptions '"${allargs[@]}"' | diffstat $diffStatArgs
elif [ "$hasColorDiff" ]; then
    # Pipe through colordiff instead of using svn --diff-cmd colordiff, because
    # svn only pipes the diff output itself, but not the diff header ("Index:
    # ...") through colordiff, and therefore the header isn't highlighted with
    # the "cvsstuff" group in .colordiffrc.
    eval svn diff --non-interactive $svnDiffOptions '"${allargs[@]}"' | colordiff | "${PAGER:-less}" --quit-on-intr --RAW-CONTROL-CHARS
else
    eval svn diff --non-interactive $svnDiffOptions '"${allargs[@]}"' | "${PAGER:-less}" --quit-on-intr --RAW-CONTROL-CHARS
fi
