#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Print the status of working copy files and directories, shortened to file /
directory names only; i.e. all paths are stripped.
Usage: "$(basename "$1")" [PATH...] [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

set -o pipefail
exec svn status "$@" | sed -e 's#\(^.\{8\}\).*/\([^/]\+$\)#\1\2#'
