#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Minimal one-line log messages with commit summary.
--no-merge	Exclude any commits that mention merge in the revision summary.
--no-color	Turn off color highlighting.
--server	Instead of local history, only list server revisions that you
		don't have yet.
Note: svn log option -v is not supported here, but also doesn't make sense here.
Usage: "$(basename "$1")" [--no-merge] [-c M | -r N[:M]] [-l|--limit ARG] [--no-color] [--server|PATH...] [-?|-h|--help]
HELPTEXT
}

: ${SVN_MERGE_COMMENT_PATTERN:=merg\\(e\\|ed\\|es\\|ing\\|eback\\)\\b}
: ${COLOR_REVISION:='[36m'}
: ${COLOR_RESET:='[0m'}
colorize()
{
    if [ "$isNoColor" ]; then
	cat
    else
	sed --unbuffered -e "s/^\\([^ ]\+\\) \\(.*\\)/${COLOR_REVISION}\\1${COLOR_RESET} \\2/"
    fi
}

typeset filter=cat
typeset isNoColor=
typeset isServerRevisions=
typeset isRevisionGiven=
typeset -a serverArgs=()
typeset -a allargs=()
while [ $# -gt 0 ]
do
    case "$1" in
	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
	--no-merge)	shift; filter="grep --line-buffered -iv ${SVN_MERGE_COMMENT_PATTERN}";;
	--no-color)	shift; isNoColor='true';;
	--server)	shift; isServerRevisions='true';;
	*)
	    if [ "$isServerRevisions" -a -d "$1" ]; then
		serverArgs=("$1")
	    else
		allargs+=("$1")
	    fi

	    case "$1" in
		--change|-c)	isRevisionGiven=t;;
		--revision|-r)	isRevisionGiven=t;;
	    esac

	    shift
	    ;;
    esac
done
if [ "$isServerRevisions" ]; then
    if [ "$isRevisionGiven" ]; then
	# The revision(s) have been passed; no need to check what's on the
	# server. Just add the repository URL.
	# Note: Passing --server when revisions are passed is superfluous;
	# Subversion will query the server, anyway. But better support this in a
	# consistent way. Without this, we would either get an unexpected list
	# of all server revisions, or a Subversion error about -r and -c being
	# mutually exclusive.
	allargs+=("${serverArgs[@]}" $(svn-url "${serverArgs[@]}"))
    else
	# Determine the range of revisions available on the server.
	allargs+=($(svn-serverrevs "${serverArgs[@]}"))
    fi
fi

set -o pipefail
svn log --non-interactive "${allargs[@]}" | sed --unbuffered -ne '
/^r[0-9]\+/{
    s/\(^r[0-9]\+\) *.*/\1 /
    N
    N
    s/\n//g
    p
}
' | $filter | colorize | less --RAW-CONTROL-CHARS
