#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Detailed log messages of my commits.
Like "svn log" filtered for my personal commits.
    -v		    Include a list of changed files.
    --grep REGEXP   Limit the commits to ones with log message that matches the
		    specified pattern.
    -i, --regexp-ignore-case
		    Match the regexp limiting patterns without regard to letters
		    case.
    -E, --extended-regexp
		    Consider the limiting patterns to be extended regular
		    expressions instead of the default basic regular
		    expressions.
    -F, --fixed-strings
		    Consider the limiting patterns to be fixed strings (don't
		    interpret pattern as a regular expression).
    --no-merge	    Exclude any commits that mention merge in the revision
		    summary.
    --server	    Instead of local history, only list server revisions that
		    you don't have yet.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[--no-merge] [-v|--verbose] [--grep REGEXP [--grep ...]] [-i|--regexp-ignore-case] [-E|--extended-regexp|-F|--fixed-strings] [-c M | -r N[:M]] [-g|--use-merge-history] [-l|--limit ARG] [--server|PATH...] [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

exec svn-log --author "${SVNUSER:-$USER}" "$@"
