#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Internal helper script. Prints the revision arguments representing all server
revisions that are not yet in the working copy.
Usage: "$(basename "$1") [PATH]"
HELPTEXT
}

case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

set -o pipefail
repositoryUrl=$(svn-url "$@") || exit $?
wcRevision=$(svn info --non-interactive "$@" | sed -n -e 's/^Revision: \(.*\)$/\1/p') || exit $?

echo "-r HEAD:$((wcRevision + 1)) $repositoryUrl"
