#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
Edit the commit message of the passed revision and update it.
Usage: "$(basename "$1")" -r REV [TARGET] [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

svn propedit svn:log --revprop "$@"
