#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Undo "svn add PATH..."; unschedules the file from addition to Subversion, but
keeps the file in the working copy.
Usage: "$(basename "$1")" [-?|-h|--help] PATH...
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

[ $# -gt 0 ] || { printUsage "$0"; exit 1; }

IFS=$'\n'
typeset -a paths=($(svn-status-files --quiet --match A))
if [ ${#paths[@]} -eq 0 ]; then
    echo >&2 "No files are scheduled for addition."
    svn-wrapper status "$@"
    exit 1
fi

# Only delete the root paths; Subversion will automatically remove any added
# children, and specifying them will cause "svn: E155010: The node '...' was not
# found."
typeset -a rootPaths=()
typeset previousPath=
for path in "${paths[@]}"
do
    [ "$previousPath" -a "${path:0:${#previousPath}}" = "$previousPath" ] || rootPaths+=("$path")
    previousPath="${path}/"
done

exec svn delete --keep-local "${rootPaths[@]}"
