#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Show the current path inside of the repository.
Usage: "$(basename "$1")" [-?|-h|--help] [PATH...]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac


[ $# -gt 0 ] || set -- .
while [ $# -gt 0 ]
do
    dirspec=$1
    shift

    [ -d "${dirspec}/.svn" ] || {
	echo >&2 "ERROR: '${dirspec}' is not a working copy"
	exit 1
    }
    type -P svn >/dev/null 2>&1 || exit 1
    'svn' info "$dirspec" 2>/dev/null | awk '
    BEGIN {
	for (i = 0; i < 16; i++) {
	    hexc[sprintf("%c", i + (i > 9 ? 55 : 48))] = i
	}
	for (i = 32; i < 127; i++) {
	    ++charset[sprintf("%c", i)]
	}
    }
    function urldecode(s,   a, b, c, d, i)
    {
	d = ""
	for (i = 1; i <= length(s); i++) {
	    c = substr(s, i, 1)
	    if (c == "%") {
		a = toupper(substr(s, ++i, 1))
		b = toupper(substr(s, ++i, 1))
		c = sprintf("%c", hexc[a] * 16 + hexc[b])
	    } else {
		sub(/\+/, " ", c)
	    }
	    d = d (c in charset ? c : " ")
	}
	return d
    }

    $1 == "URL:" {
	repositoryUrl = $2
    }
    $1 == "Repository" && $2 == "Root:" {
	repositoryRoot = $3
    }

    END {
	repositoryPath = urldecode(substr(repositoryUrl, length(repositoryRoot) + 1))
	print repositoryPath
    }
'
done
