#!/bin/bash

shopt -qs extglob 2>/dev/null

printUsage()
{
    cat <<HELPTEXT
Show log message and textual diff for a particular commit.
With -b (ignore space change) and -w (ignore all white space) options.
Can also show statistics with --stat, --numstat and --shortstat.
--no-color	Turn off colored diff.
Usage: "$(basename "$1")" [-b] [-w] [[-r|--revision] REV [[-r|--revision] REV ...]] [--stat|--numstat|--shortstat] [--no-color] [-?|-h|--help]
HELPTEXT
}

case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

typeset -a allargs=()
typeset -a diffargs=()
typeset -a revisions=()
while [ $# -gt 0 ]
do
    case "$1" in
	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
	--change|-c)	shift; revisions+=("$1"); shift;;
	--revision|-r)	shift; revisions+=("$1"); shift;;
	?(r)+([0-9]))	       revisions+=("${1#r}"); shift;;
	-b|-w|--stat|--numstat|--shortstat)
			diffargs+=("$1"); shift;;
	*)
	    allargs+=("$1")
	    shift
	    ;;
    esac
done
shift

set -o pipefail
if [ ${#revisions[@]} -eq 0 ]; then
    echo >&2 "ERROR: Must specify REV."; printUsage "$0"; exit 1
else
    for revision in "${revisions[@]}"
    do
	svn-wrapper log --incremental --change "$revision" "${allargs[@]}" && svn-dp --change "$revision" "${diffargs[@]}" "${allargs[@]}"
    done | less --quit-on-intr --RAW-CONTROL-CHARS
fi
