#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
Highlights diff output red/green. 
With -b (ignore space change) and -w (ignore all white space) options. 
Can also show statistics with --stat, --numstat and --shortstat. 
Usage: "$(basename "#1")" [-b] [-w] [-c M | -r N[:M]] [--stat|--numstat|--shortstat] [TARGET[@REV]...] [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

diffOptions=
diffStatArgs=

# Highlight diff output if available. 
colordiffCommand=
if which colordiff >/dev/null 2>&1; then
    colordiffCommand='--diff-cmd colordiff'
fi

# Simplify setting common diff options (that do not overlap with svn options). 
while [ $# -gt 0 ]
do
    case "$1" in
	-b)
	    shift
	    diffOptions="${diffOptions:--x -u }${diffOptions:+ }-b"
	    ;;
	-w)
	    shift
	    diffOptions="${diffOptions:--x -u }${diffOptions:+ }-w"
	    ;;
	# Note: --ignore-eol-style seems to be handled internally by svn; it is
	# not supported by GNU diff or colordiff. 
	--stat)
	    shift
	    diffStatArgs='-C'
	    ;;
	--numstat)
	    shift
	    diffStatArgs='-C -f0'
	    ;;
	--shortstat)
	    shift
	    diffStatArgs='-C -s'
	    ;;
	*)  break;;
    esac
done

if [ "$diffStatArgs" ]; then
    svn diff "$diffOptions" "$@" | diffstat $diffStatArgs
else
    svn diff "$diffOptions" $colordiffCommand "$@" | less --RAW-CONTROL-CHARS
fi
