#!/bin/bash

shopt -qs extglob 2>/dev/null

printUsage()
{
    cat <<HELPTEXT
One-line log messages with author, date and commit summary. 
--no-merge	Exclude any commits that mention merge in the revision summary. 
--author regexp	Limit to commits by author. 
--no-list-author Omit the author name from the log; happens automatically if
		regexp is literal text. 
--server	Instead of local history, only list server revisions that you
		don't have yet. 
Note: svn log option -v is not supported here, but also doesn't make sense here. 
Usage: "$(basename "$1")" [--no-merge] [--author regexp] [--no-list-author] [-c M | -r N[:M]] [-l|--limit ARG] [--server|PATH...] [-?|-h|--help]
HELPTEXT
}

: ${COLOR_REVISION:='[36m'}
: ${COLOR_AUTOR_DATE:='[32m'}
: ${COLOR_RESET:='[0m'}
colorize()
{
    sed --unbuffered -e 's/^\(r[0-9]\+\) \(([^)]\+)\) \(.*\)/'"${COLOR_REVISION}\\1${COLOR_RESET} ${COLOR_AUTOR_DATE}\\2${COLOR_RESET} \\3/"
}

typeset filter=cat
typeset isListAuthor=true
typeset authorArgs=
typeset isServerRevisions=
typeset -a allargs=()
while [ $# -gt 0 ]
do
    case "$1" in
	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
	--no-merge)	shift; filter='grep --line-buffered -iv merg\(e\|ed\|es\|ing\)\b';;
	--no-list-author)	shift; isListAuthor=;;
	--author)	shift;
			authorArgs=$1;
			shift;
			# DWIM: When the author is no regexp, omit the known
			# name from the log. 
			[[ "$authorArgs" == +([- _a-zA-Z]) ]] && isListAuthor=
			;;
	--server)	shift; isServerRevisions='true';;
	*)
	    allargs+=("$1")
	    shift
	    ;;
    esac
done
if [ "$isServerRevisions" ]; then
    allargs+=($(svn-serverrevs))
fi

readonly today=$(date +%F)
svn log --non-interactive "${allargs[@]}" | sed --unbuffered -n -e "${authorArgs:+/^r[0-9]\+ | [^|]*${authorArgs}[^|]* |/!d}" -e '
/^r[0-9]\+/{
'"/ | ${today} /  "'s/\(^r[0-9]\+\) *| *\([^ |]\+\) | *[^ |]\+ \([^ |]\+\) [^|]*|.*/\1 ('"${isListAuthor:+\2, }"'\3) /
    t done
		    s/\(^r[0-9]\+\) *| *\([^ |]\+\) | *\([^ |]\+\)[^|]*|.*/\1 ('"${isListAuthor:+\2, }"'\3) /
:done
    N
    N
    s/\n//g
    p
}
' | $filter | colorize | less --RAW-CONTROL-CHARS
