#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Rewrite working copy URL metadata, replacing the first occurrence of PATTERN
with REPLACEMENT.
Usage: "$(basename "$1")" PATTERN REPLACEMENT [PATH...] [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

[ $# -ge 2 ] || { printUsage "$0"; exit 1; }

pattern=$1; shift
replacement=$1; shift

url=$(svn info --non-interactive "$@" | sed -n -e 's/^URL: \(.*\)$/\1/p') || exit $?
newUrl=$(printf %s "$url" | sed -e "s/${pattern//\//\\/}/${replacement//\//\\/}/") || exit $?

if [ "$newUrl" = "$url" ]; then
    echo >&2 "$*${*:+: }No change for $url"
    exit
fi

svn relocate --username "${SVNUSER:-$USER}" "$url" "$newUrl" "$@" || exit $?
svn info --non-interactive "$@" | sed -n -e 's/^URL:/new &/p'
