#!/bin/bash
set -o pipefail

printUsage()
{
    cat <<HELPTEXT
Use the pager for help output.
HELPTEXT
    echo
    printf 'Usage: %q %s\n' "$(basename "$1")" '[-v|--verbose] [SUBCOMMAND...] [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

exec svn help "$@" | "${PAGER:-less}"
