#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
One-line log messages of my commits with date and commit summary.
Like "svn lg" filtered for my personal commits.
-v		Include a list of changed files.
--grep regexp   Limit the commits to ones with log message that matches the
		specified pattern.
--no-merge	Exclude any commits that mention merge in the revision summary.
--server	Instead of local history, only list server revisions that you
		don't have yet.
Usage: "$(basename "$1")" [--no-merge] [-v|--verbose] [--grep regexp] [-c M | -r N[:M]] [-l|--limit ARG] [--server|PATH...] [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

exec svn-lg --author "${SVNUSER:-$USERNAME}" "$@"
