#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
Put files under version control by copying the history of an existing element. 
Usage: "$(basename "$1")" [-?|-h|--help] SRC[@REV] PATH...
Example: "$(basename "$1")" path/to/{Original,Cloned}File.txt
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

src=$1
shift
[ $# -gt 0 ] || { printUsage "$0"; exit 1; }

status=0
for filespec
do
    tmp="${filespec}.tmp"
    mv "$filespec" "$tmp" || { status=1; continue; }
    svn copy --non-interactive "$src" "$filespec" || { status=1; mv "$tmp" "$filespec"; continue; }
    mv "$tmp" "$filespec" || { status=1; continue; }
done
exit $status
