#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Extract all Subversion revisions from stdin, and present them one per line.
Usage: "$(basename "$1")" [-?|-h|--help]
HELPTEXT
}

case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

export GREP_OPTIONS=
grep -o -e '\(^\|[^[:alpha:]]\)r[[:digit:]]\+\([^[:alpha:]]\|$\)' | grep -o 'r[[:digit:]]\+'
