#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
Remove PATH or all files in the current directory from the working copy, and
skip them on future updates. 
Note: To check whether a directory has been pruned, use
    svn info | grep ^Depth:
      To list the pruned files, use
    svn ls
Usage: "$(basename "$1")" [PATH...] [-?|-h|--help]
HELPTEXT
}

case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

svn update --set-depth=empty "$@"
