#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Include the entire, recursive PATH or everything in the current directory in
future updates of the working copy.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[PATH...] [-?|-h|--help]'
}

case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

exec svn update --set-depth=infinity "$@"
