#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Highlights diff output red/green.
With -b (ignore space change) and -w (ignore all white space) options.
Can also show statistics with --stat, --numstat and --shortstat.
--no-color	Turn off colored diff.

Default is working copy to last commit; use
-r PREV to diff working copy with previous commit and
-r PREV:COMMITTED (or svn dp) to show change in previous commit, and
-r REV:COMMITTED to show changes across revisions.

Usage: "$(basename "#1")" [-b] [-w] [-c M | -r N[:M]] [--stat|--numstat|--shortstat] [--no-color] [TARGET[@REV]...] [-?|-h|--help]
HELPTEXT
}

diffOptions=
diffStatArgs=

# Highlight diff output if available.
hasColorDiff=
which colordiff >/dev/null 2>&1 && hasColorDiff=t

typeset -a allargs=()
# Simplify setting common diff options (that do not overlap with svn options).
while [ $# -gt 0 ]
do
    case "$1" in
	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
	-b)
	    shift
	    diffOptions="${diffOptions}${diffOptions:+ }-b"
	    ;;
	-w)
	    shift
	    diffOptions="${diffOptions}${diffOptions:+ }-w"
	    ;;
	# Note: --ignore-eol-style seems to be handled internally by svn; it is
	# not supported by GNU diff or colordiff.
	--stat)
	    shift
	    diffStatArgs='-C'
	    ;;
	--numstat)
	    shift
	    diffStatArgs='-C -f0'
	    ;;
	--shortstat)
	    shift
	    diffStatArgs='-C -s'
	    ;;
	--no-color)
	    shift
	    hasColorDiff=
	    ;;
	*)
	    allargs+=("$1")
	    shift
	    ;;
    esac
done

# Note: diffOptions can be passed as a single argument "-x -u -b" as well as the
# two-arg -x "-u -b", but not as individual arguments.
# Note: Must not pass an empty "" argument to svn, or the filtering for TARGET
# doesn't work any more.
set -o pipefail
[ "$diffOptions" ] && svnDiffOptions="-x \"-u ${diffOptions}\""
if [ "$diffStatArgs" ]; then
    eval svn diff --non-interactive $svnDiffOptions '"${allargs[@]}"' | diffstat $diffStatArgs
elif [ "$hasColorDiff" ]; then
    # Pipe through colordiff instead of using svn --diff-cmd colordiff, because
    # svn only pipes the diff output itself, but not the diff header ("Index:
    # ...") through colordiff, and therefore the header isn't highlighted with
    # the "cvsstuff" group in .colordiffrc.
    svn diff --non-interactive $svnDiffOptions "${allargs[@]}" | colordiff | less --quit-on-intr --RAW-CONTROL-CHARS
else
    svn diff --non-interactive $svnDiffOptions "${allargs[@]}" | less --quit-on-intr --RAW-CONTROL-CHARS
fi
