#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
Show files below the current / passed repository's root that (wrongly) have a
svn:mergeinfo property.
Usage: "$(basename "$1")" [PATH] [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

rootdir=$(svn-root "$@") || exit $?
svn propget --recursive svn:mergeinfo "$rootdir" | sed -e '/ - \//!d' -e '/^\. - \//d' -e "/^${rootdir//\//\\/} - \//d" -e 's+ - /.*$++'
