#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Find merge candidates of my commits in SOURCE that still need merging into the
working copy, and merge them back.
If the merge aborts with a conflict in between, just re-execute the same command
with the --continue argument added; this avoids that the original commit message
template (for all merged revisions) gets overwritten.
HELPTEXT
printf 'Usage: %q %s\n' "$(basename "$1")" '[--continue] [-v|--verbose] [--grep REGEXP [--grep ...]] [-i|--regexp-ignore-case] [-E|--extended-regexp|-F|--fixed-strings] [-c M | -r N[:M]] [-l|--limit ARG] SOURCE[@REV] [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

exec svn-merge-back --author "${SVNUSER:-$USER}" "$@"
