#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
List revision number, author, and date of the last commit.
Usage: "$(basename "$1")" [TARGET[@REV]...] [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

# Omit the file size; a plain 'll' tells this, too.
# The commit date is different from the file's date in the working copy and may
# be important, to leave that in.
set -o pipefail
svn ls -v "$@" | cut -c 1-20,31-
