#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
List unversioned files. Show a summary for unversioned directories
or with -l|--long-format the entire subdir contents.
With -x|--no-ignore also ignored files.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[-l|--long-format] [-x|--no-ignore] [PATH...] [-?|-h|--help]'
}

isLongFormat=
additionalArgs=
while [ $# -ne 0 ]
do
    case "$1" in
	--help|-h|-\?)	    shift; printUsage "$0"; exit 0;;
	--long-format|-l)   shift; isLongFormat=t;;
	--no-ignore|-x)	    shift; additionalArgs="${additionalArgs}${additionalArgs:+ }--no-ignore";;
	*)		    break;;
    esac
done


set -o pipefail
svn status --non-interactive $additionalArgs "$@" | grep '^[?I]' | cut -c 9- | while read filespec
do
    if [ -d "$filespec" ]; then
	if [ "$isLongFormat" ]; then
	    find "$filespec"
	else
	    fileNum=$(find "$filespec" -type f | wc -l)
	    dirsize=$(du -s --human-readable -- "$filespec" | cut -f 1)
	    echo "$filespec [directory; $fileNum file$([ $fileNum -eq 1 ] || printf 's'), ${dirsize}]"
	fi
    else
	echo "$filespec"
    fi
done
