#!/bin/bash

shopt -qs extglob 2>/dev/null

printUsage()
{
    cat <<HELPTEXT
One-line log messages with author, date and commit summary.
-R, --reverse	Show in reverse order.
--no-merge	Exclude any commits that mention merge in the revision summary.
--author REGEXP	Limit to commits by author.
--no-list-author Omit the author name from the log; happens automatically if
		REGEXP is literal text.
--no-list-date	Omit the date from the log.
--no-color	Turn off color highlighting.
--server	Instead of local history, only list server revisions that you
		don't have yet.
Note: svn log option -v is not supported here, but also doesn't make sense here.
Usage: "$(basename "$1")" [--no-merge] [--author REGEXP] [--no-list-author] [--no-list-date] [-c M | -r N[:M]] [-g|--use-merge-history] [-l|--limit ARG] [--no-color] [--server] [PATH...] [-?|-h|--help]
HELPTEXT
}

: ${SVN_MERGE_COMMENT_PATTERN:=merg\\(e\\|ed\\|es\\|ing\\|eback\\)\\b}
: ${COLOR_REVISION:='[36m'}
: ${COLOR_AUTOR_DATE:='[32m'}
: ${COLOR_RESET:='[0m'}
colorize()
{
    if [ ! "$isListAuthor" -a ! "$isListDate" ]; then
	colorizer='s/^\(r[0-9]\+\) \(.*\)/'"${COLOR_REVISION}\\1${COLOR_RESET} \\2/"
    else
	colorizer='s/^\(r[0-9]\+\) \(([^)]\+)\) \(.*\)/'"${COLOR_REVISION}\\1${COLOR_RESET} ${COLOR_AUTOR_DATE}\\2${COLOR_RESET} \\3/"
    fi
    sed --unbuffered -e "$colorizer"
}

typeset limit=
typeset limitFilter=cat
typeset filter=cat
typeset isListAuthor=t
typeset isListDate=t
typeset authorArgs=
typeset isServerRevisions=
typeset -a serverArgs=
typeset colorize=colorize
typeset -a allargs=()
while [ $# -gt 0 ]
do
    case "$1" in
	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
	--limit|-l)	shift; limit=$1; shift;;
	--verbose|-v)	echo >&2 "Extra information via $1 is not supported here!"; exit 2;;
	--reverse|-R)	shift; allargs+=('--revision' '1:BASE');;
	--no-merge)	shift; filter="grep --line-buffered -iv ${SVN_MERGE_COMMENT_PATTERN}";;
	--no-color)	shift; colorize='cat';;
	--no-list-author)	shift; isListAuthor=;;
	--no-list-date)		shift; isListDate=;;
	--author)	shift;
			authorArgs=$1;
			shift;
			# DWIM: When the author is no regexp, omit the known
			# name from the log.
			[[ "$authorArgs" == +([- _a-zA-Z]) ]] && isListAuthor=
			;;
	--server)	shift; isServerRevisions='true';;
	*)
	    if [ "$isServerRevisions" -a -d "$1" ]; then
		serverArgs=("$1")
	    else
		allargs+=("$1")
	    fi
	    shift
	    ;;
    esac
done
if [ "$isServerRevisions" ]; then
    allargs+=($(svn-serverrevs "${serverArgs[@]}"))
fi
if [ "$limit" ]; then
    if [ "$filter" = 'cat' -a ! "$authorArgs" ]; then
	# When we do not need to do revision filtering, we can let svn log handle
	# the limit itself.
	allargs+=(--limit $limit)
    else
	limitFilter="sed ${limit}q"
    fi
fi

if [ ! "$isListAuthor" -a ! "$isListDate" ]; then
    format=
else
    format="(${isListAuthor:+\2${isListDate:+, }}${isListDate:+\3}) "
fi

readonly today=$(date +%F)
set -o pipefail
svn log --non-interactive "${allargs[@]}" 2> >(grep -Fv 'Write error: Broken pipe') | sed --unbuffered -n -e "${authorArgs:+/^r[0-9]\+ | [^|]*${authorArgs}[^|]* |/!d}" -e '
/^r[0-9]\+/{
'"/ | ${today} /  "'s/\(^r[0-9]\+\) *| *\([^ |]\+\) | *[^ |]\+ \([^ |]\+\) [^|]*|.*/\1 '"${format}"'/
    t done
		    s/\(^r[0-9]\+\) *| *\([^ |]\+\) | *\([^ |]\+\)[^|]*|.*/\1 '"${format}"'/
:done
    N
    N
    s/\n//g
    p
}
' | $filter | $limitFilter | $colorize | less --RAW-CONTROL-CHARS
