#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Show who created / renamed the passed file.
Usage: "$(basename "$1")" PATH [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

