#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
Put single files under version control, without recursing into subdirs. 
Usage: "$(basename "$1")" [-?|-h|--help] PATH...
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

status=0
for filespec
do
    if [ ! -d "$filespec" ]; then
	dirspec=$(dirname -- "$filespec")
	if svn status "$dirspec" | grep -q '^\?' > /dev/null; then
	    # The directory of the file to be added is not yet under version
	    # control; add it first. 
	    svn add --non-recursive "$dirspec" || { status=1; continue; }
	fi
    fi

    svn add --non-recursive "$filespec" || { status=1; continue; }
done
exit $status
