#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
Cancel a Replaced file status and turn it to the normal Modified.
Usage: "$(basename "$1")" [-?|-h|--help] PATH...
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

[ $# -gt 0 ] || { printUsage "$0"; exit 1; }

status=0
for filespec
do
    if ! svn list --non-interactive "$filespec" >/dev/null 2>&1; then
	echo >&2 "${filespec}: doesn't yet exist as a revision"
	status=1; continue
    fi

    tmp="${filespec}.tmp"
    cp "$filespec" "$tmp" || { status=1; continue; }
    svn revert --non-interactive "$filespec" >/dev/null || { status=1; mv "$tmp" "$filespec"; continue; }
    mv "$tmp" "$filespec" || { status=1; continue; }
    svn status --non-interactive "$filespec"
done
exit $status
