#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
List all svn command extensions and newly defined commands. 
Usage: "$(basename "$1")" [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

scriptDir=$(dirname -- "$0")
[ "$scriptDir" = "." ] && readonly scriptDir=$(dirname -- $(which -- "$0")) || readonly scriptDir=$(cd "$scriptDir" && echo "${PWD}") || { echo >&2 "ERROR: Cannot determine absolute script dirspec!"; exit 2; }
[ -d "$scriptDir" ] || { echo >&2 "ERROR: Cannot determine script directory!"; exit 2; }

for svnalias in "$scriptDir/"svn-*
do
    [ -x "$svnalias" ] || continue

    # Filter out backup files. 
    case "$(basename -- "$svnalias")" in
	    *.[1-2][0-9][0-9][0-9][0-9][0-9][0-9][0-9][a-z])    continue;;
    esac 

    echo "[01m${svnalias##*svn-}[0m"
    sed -e '1,/<<HELPTEXT$/d;/^Usage: /d;/^HELPTEXT$/{s/.*//;q}' "$svnalias"
done | less --RAW-CONTROL-CHARS
