#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Show the root dir of this working copy.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[-?|-h|--help] [PATH...]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

set -o pipefail
if [ -z "$1" ]; then
    wcpath=.
elif [ -d "$1" ]; then
    wcpath=$1
else
    wcpath="$(dirname -- "$1")"
fi
dirspec=$(cd "$wcpath" && echo "$PWD")
if [ -d "${dirspec}/.svn" ]; then
    # Detection for Subversion <= 1.6 (where there are .svn directories in every
    # directory of the working copy), or when in the working copy root.
    prevDirspec=
    while [ "$prevDirspec" != "$dirspec" -a -d "${dirspec}/.svn" ]
    do
	prevDirspec=$dirspec
	dirspec=$(dirname -- "$dirspec")
    done
    printf '%s\n' "$prevDirspec"
else
    # Detection for Subversion >= 1.7, where there's only a single .svn
    # directory in the working copy root.
    prevDirspec=
    while [ "$prevDirspec" != "$dirspec" ]
    do
	if [ -d "${dirspec}/.svn" ]; then
	    printf '%s\n' "$dirspec"
	    exit 0
	fi

	prevDirspec=$dirspec
	dirspec=$(dirname -- "$dirspec")
    done

    echo >&2 "Not inside a working copy${1:+: }${1:-.}"
    exit 1
fi
