#!/bin/bash

shopt -qs extglob 2>/dev/null

printUsage()
{
    cat <<HELPTEXT
Show the files modified in passed revision or revision range.
--author REGEXP	Limit to commits by author.
--server	Instead of local history, only consider server revisions that
		you don't have yet.
Usage: "$(basename "$1")" [--author REGEXP] [-c M | -r N[:M]] [-l|--limit ARG] [--server|PATH...] [-?|-h|--help]
Example: "$(basename "$1")" --author mike -r {2012-04-01:HEAD}
HELPTEXT
}

typeset authorArgs=
typeset isServerRevisions=
typeset isRevisionGiven=
typeset -a serverArgs=()

typeset -a allargs=()
while [ $# -gt 0 ]
do
    case "$1" in
	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
	--author)	shift; authorArgs=$1; shift;;
	--server)	shift; isServerRevisions='true';;
	*)
	    if [ "$isServerRevisions" -a -d "$1" ]; then
		serverArgs=("$1")
	    else
		allargs+=("$1")
	    fi

	    case "$1" in
		--change|-c)	isRevisionGiven=t;;
		--revision|-r)	isRevisionGiven=t;;
	    esac

	    shift
	    ;;
    esac
done
if [ "$isServerRevisions" ]; then
    if [ "$isRevisionGiven" ]; then
	# The revision(s) have been passed; no need to check what's on the
	# server. Just add the repository URL.
	# Note: Passing --server when revisions are passed is superfluous;
	# Subversion will query the server, anyway. But better support this in a
	# consistent way. Without this, we would either get an unexpected list
	# of all server revisions, or a Subversion error about -r and -c being
	# mutually exclusive.
	allargs+=("${serverArgs[@]}" $(svn-url "${serverArgs[@]}"))
    else
	# Determine the range of revisions available on the server.
	allargs+=($(svn-serverrevs "${serverArgs[@]}"))
    fi
fi

set -o pipefail
svn log --non-interactive --verbose "${allargs[@]}" | if [ "$authorArgs" ]; then
    awk -v authorExpr="$authorArgs" '
/^r[0-9]+ / {
    user = $3
}
/^Changed paths:/,/^$/ {
    if ($0 == "" || $0 ~ "^Changed paths:") {
	next
    }
    if (user ~ authorExpr) {
	print $0
    }
}
'
else
    sed -ne '
/^Changed paths:/,/^$/ {
    /^$/d
    /^Changed paths:/d
    p
}
'
fi | sort -k 2 -u | "${PAGER:-less}" --quit-on-intr --RAW-CONTROL-CHARS
