#!/bin/bash

shopt -qs extglob 2>/dev/null

printUsage()
{
    cat <<HELPTEXT
Diff with predecessor, either current COMMITTED revision to PREV, or
revision REV to its predecessor.
With -b (ignore space change) and -w (ignore all white space) options.
Can also show statistics with --stat, --numstat and --shortstat.
--no-color	Turn off color highlighting.
Note: The [@REV] is only a revision peg for use on the server; you cannot
specify a local revision with it.
Usage: "$(basename "$1")" [-b] [-w] [[-r|--revision] REV [[-r|--revision] REV ...]] [--stat|--numstat|--shortstat] [--no-color] [TARGET[@REV]...] [-?|-h|--help]
HELPTEXT
}

: ${COLOR_HEADER:='[36m'}
: ${COLOR_RESET:='[0m'}
typeset -a allargs=()
typeset -a revisions=()
while [ $# -gt 0 ]
do
    case "$1" in
	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
	--no-color)
			allargs+=("$1")	# Pass option along to my svn diff wrapper.
			shift
			# And clear all colors used here.
			for color in ${!COLOR_@}; do
			    unset $color
			done
			;;
	--change|-c)	shift; revisions+=("$1"); shift;;
	--revision|-r)	shift; revisions+=("$1"); shift;;
	?(r)+([0-9]))	       revisions+=("${1#r}"); shift;;
	*)
	    allargs+=("$1")
	    shift
	    ;;
    esac
done

diffHandlingMoves()
{
    revision=$1; shift

    svn-wrapper diff --change $revision "$@" && return 0

    # svn diff returned an error; it may have been unable to find the repository
    # location for the predecessor, in case it was moved or renamed.
    # The svn-renamed gives us the move information. To avoid superfluous
    # processing, start the query at $revision and limit the log output to the
    # minimal 2 entries necessary: The log of $revision (containing the move
    # info), and the predecessor (containing the predecessor revision).
    svn-renamed --non-interactive --revision "${revision}:1" --limit 2 "$@" | {
	IFS=$'\t'
	read -r currentRev currentPath
	read -r previousRev previousPath
	[ "$previousRev" -a "$previousPath" -a "$previousRev" ] || return 1
	echo >&2 "svn-dp: Following file move from ${previousPath} in revision ${previousRev}"
	svn-wrapper diff --revision ${previousRev#r}:${revision} --old="^${previousPath}" --new="^${currentPath}"
    }
}

set -o pipefail
if [ ${#revisions[@]} -eq 0 ]; then
    svn-wrapper diff -r PREV:COMMITTED "${allargs[@]}"
elif [ ${#revisions[@]} -eq 1 ]; then
    diffHandlingMoves $revisions "${allargs[@]}"
else
    typeset isFirstEntry='true'
    for revision in "${revisions[@]}"
    do
	[ "$isFirstEntry" ] && isFirstEntry= || echo
	echo "${COLOR_HEADER}revision r${revision}${COLOR_RESET}"
	diffHandlingMoves $revision "${allargs[@]}"
    done | less --quit-on-intr --RAW-CONTROL-CHARS
fi
