#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Show the revision and dirty state of the repository.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[-?|-h|--help] [PATH...]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

set -o pipefail
modifiedFiles=$(svn status --non-interactive -q "$@") || exit $?
[ "$modifiedFiles" ] && dirty='-dirty' || dirty=
revision=$(svn info --non-interactive "$@" | sed -ne 's/^Revision: //p') || exit $?
printf 'r%s%s\n' "$revision" "$dirty"
