#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Show files below the current / passed repository's root that (wrongly) have a
svn:mergeinfo property.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[PATH] [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

rootdir=$(svn-root "$@") || exit $?
svn propget --recursive svn:mergeinfo "$rootdir" | sed -e '/ - \//!d' -e '/^\. - \//d' -e "/^${rootdir//\//\\/} - \//d" -e 's+ - /.*$++'
