#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
List unversioned files. Show a summary for unversioned directories
or with -l the entire subdir contents.
With -x|--no-ignore also ignored files.
Usage: "$(basename "$1")" [-l] [-x|--no-ignore] [PATH...] [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

isLongFormat=
if [ "$1" = "-l" ]; then
    isLongFormat='true'
    shift
fi
additionalArgs=
if [ "$1" = "-x" ]; then
    additionalArgs="${additionalArgs}${additionalArgs:+ }--no-ignore"
    shift
fi

set -o pipefail
svn status --non-interactive $additionalArgs "$@" | grep '^[?I]' | cut -c 9- | while read filespec
do
    if [ -d "$filespec" ]; then
	if [ "$isLongFormat" ]; then
	    find "$filespec"
	else
	    fileNum=$(find "$filespec" -type f | wc -l)
	    dirsize=$(du -s --human-readable -- "$filespec" | cut -f 1)
	    echo "$filespec [directory; $fileNum file$([ $fileNum -eq 1 ] || printf 's'), ${dirsize}]"
	fi
    else
	echo "$filespec"
    fi
done
