#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Remove PATH or all files in the current directory from the working copy, and
skip them on future updates.
Note: To check whether a directory has been pruned, use
    svn info | grep ^Depth:
      To list the pruned files, use
    svn ls
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[PATH...] [-?|-h|--help]'
}

case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

exec svn update --set-depth=empty "$@"
