#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Show the current branch / tag, revision and dirty state of the repository.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[-?|-h|--help] [PATH...]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

set -o pipefail
branch=$(svn-branchname "$@") || exit $?
describe=$(svn-describe "$@") || exit $?
printf '%s-%s\n' "$branch" "$describe"
