#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Print the status of the working copy and potential newer revisions (*) on the
server.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[PATH...] [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

exec svn status --show-updates "$@"
