#!/bin/bash

svn add "$@" || exit $?

if [ "$(uname -o 2>/dev/null)" = "Cygwin" ]; then
    # Note: This ignores recursive adding of files contained in added
    # directories. As a workaround, use for those "svn addonly" on the directory
    # first.
    for filespec
    do
	if [ -f "$filespec" ]; then
	    extension=${filespec##*.}
	    if [[ ";${PATHEXT^^};" = *";.${extension^^};"* ]]; then
		echo "$filespec is executable"
	    else
		# According to Windows, the file is not executable, but Cygwin
		# treats all files on the Windows file systems as executable
		# (unless explicitly modified via chmod), and Subversion's
		# Automatic Property Setting feature adds svn:executable
		# properties. Strip them off for this file.
		svn propdel svn:executable "$filespec"
	    fi
	fi
    done
fi
