#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
Remove unversioned files and empty directories, 
with -r also any unversioned directory trees. 
With -x|--no-ignore also ignored files. 
Usage: "$(basename "$1")" [-r] [-x|--no-ignore] [PATH...] [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

recursiveFlag=
if [ "$1" = "-r" ]; then
    recursiveFlag='-r'
    shift
fi
additionalArgs=
if [ "$1" = "-x" ]; then
    additionalArgs="${additionalArgs}${additionalArgs:+ }--no-ignore"
    shift
fi

svn status --non-interactive $additionalArgs "$@" | grep '^[?I]' | cut -c 9- | while read victim
do
    if [ -d "$victim" -a -z "$recursiveFlag" ]; then
	rmdir -- "$victim" && echo "$victim"
    else
	rm $recursiveFlag -- "$victim" && echo "$victim"
    fi
done
