#!/bin/bash
set -o pipefail

lastLocalRevision=$(svn info "$@" | sed -n -e 's/^Last Changed Rev: \(.*\)$/\1/p') || exit $? 
repositoryUrl=$(svn info "$@" | sed -n -e 's/^URL: \(.*\)$/\1/p') || exit $? 

TMPFILE=$(mktemp --tmpdir "$(basename -- "$0")-XXXXXX" 2>/dev/null || echo "${TEMP:-/tmp}/$(basename -- "$0").$$")
lastRepoRevision=$(svn info "$@" "$repositoryUrl" | tee "$TMPFILE" | sed -n -e 's/^Last Changed Rev: \(.*\)$/\1/p') || exit $?

GREP_OPTIONS=
grep -e '^URL: ' -e '^Revision: ' -e '^Last Changed ' "$TMPFILE"
echo
if [ $lastLocalRevision -eq $lastRepoRevision ]; then
    echo "You have the latest revision r$lastLocalRevision that is also on the server."
else
    echo "You are $((lastRepoRevision - lastLocalRevision)) revision(s) behind the server, which has r$lastRepoRevision"
fi
