#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
Verbose log messages. 
Use -v to include a list of changed files. 
Usage: "$(basename "$1")" [--no-merge] [-v|--verbose] [-c M | -r N[:M]] [-l|--limit ARG] [PATH...] [-?|-h|--help]
HELPTEXT
}

mergeFilter()
{
    sed -e '
/^revision r[0-9]\+$/ {
    h
    d
}
/^Author:/ {
    H
    d
}
/^Date:/ {
    N
    H
    d
}
/[Mm]erg\(e\|ed\|es\|ing\)\b/ {
    s/^.*$/MERGE/
    h
    d
}

x
/MERGE/ {
    x
    d
}
/^$/!p
s/^.*$//
x
'
}

filter=cat
colorHeader='[36m'
colorFileAdded='[32m'
colorFileChanged='[34m'
colorFileRemoved='[31m'
colorReset='[0m'
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
    --no-merge)		shift; filter='mergeFilter';;
esac

#svn log "$@" | sed -e '
cat /tmp/svn| sed -e '
/^r[0-9]\+/{
    s/\(^r[0-9]\+\) *| *\([^|]\+\) *| *\([^|]\+\) *|.*/revision \1\nAuthor: \2\nDate:   \3 /
}
/^Changed paths:/,/^$/ {
    /^Changed paths:/{
	s/^/\n/
	h
	d
	b
    }
    H
    d
    b
}
/^-\+$/g
' | $filter | sed -e "
s/^revision r[0-9]\\+$/${colorHeader}\\0${colorReset}/
/^Changed paths:/,/^\$/ {
    s/^ \\+A .*\$/${colorFileAdded}\\0${colorReset}/
    s/^ \\+M .*\$/${colorFileChanged}\\0${colorReset}/
    s/^ \\+R .*\$/${colorFileRemoved}\\0${colorReset}/
}
" | less --RAW-CONTROL-CHARS
