#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Try to apply a patch to the root of this working copy and print dry-run results.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" 'patchfile [...] [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

export SVN_APPLYR_PATCH_OPTIONS='--dry-run'
exec svn-applyr "$@"
