#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Undo a (range of) commits by doing a reverse merge.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[-c M[,N...] | -r N:M ...] [SOURCE[@REV]] [-?|-h|--help]'
}

typeset -a allargs=()
typeset -a revisions=()
typeset -a changes=()
while [ $# -ne 0 ]
do
    case "$1" in
	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
	--change|-c)	shift
			if [ ${#changes[@]} -eq 0 ]; then
			    changes=("-${1#-}")
			else
			    changes=("${changes[0]},-${1#-}")
			fi
			shift
			;;
	--revision|-r)	shift
			# N:M
			N=${1%:*}
			M=${1#*:}
			if [ ! "${M#r}" ]; then
			    changes+=("-$N")
			elif [ ${N#r} -gt ${M#r} ]; then
			    revisions+=("$1")
			else
			    revisions+=("$M:$N")
			fi
			shift
			;;
	*)		allargs+=("$1")
			shift
			;;
    esac
done
if [ ${#allargs[@]} -eq 0 ]; then
    allargs=("$(svn-root)") || exit $?
fi

# The working copy should be up to date, at a single revision.
svn-up "${allargs[@]}" || exit $?
svn merge ${revisions:+--revision} "${revisions[@]}" ${changes:+--change} "${changes[@]}" "${allargs[@]}"
status=$?   # Continue with building the commit message template; we might still want to commit after resolving any conflicts.

commitMessage=svn-commit.tmp
if [ -e "$commitMessage" ]; then
    # The commit message template has already been created; do not override it
    # with the now reduced number of still outstanding merge revisions.
    exit $status
fi

reformattedChanges="${changes[0]//-/}"
if [ "$reformattedChanges" ]; then
    typeset -a changesList=(${reformattedChanges//,/ })
else
    typeset -a changesList=()
fi

typeset -a mergeRevisions=("${changesList[@]}" "${revisions[@]}")
if [ ${#mergeRevisions[@]} -eq 1 -a "${mergeRevisions[*]//:/}" = "${mergeRevisions[*]}" ]; then
    printf 'Revert %s: ' "r${mergeRevisions[0]#r}"
    eval 'svn-log --format noheader' "${mergeRevisions[@]/#/-r }" '"${allargs[@]}"'
else
    mergeRevisionsList="${mergeRevisions[*]//r/}"
    mergeRevisionsList="r${mergeRevisionsList/ /, r}"
    mergeRevisionsList="${mergeRevisionsList/:/:r}"
    printf 'Revert revisions %s\n\n' "${mergeRevisionsList}"
    eval 'svn-log --format merge' "${mergeRevisions[@]/#/-r }" '"${allargs[@]}"'
fi > "$commitMessage"

exit $status
