#!/bin/bash

shopt -qs extglob 2>/dev/null

printUsage()
{
    cat <<HELPTEXT
Show the files modified in passed revision or revision range.
--author regexp	Limit to commits by author.
--server	Instead of local history, only consider server revisions that
		you don't have yet.
Usage: "$(basename "$1")" [--author regexp] [-c M | -r N[:M]] [-l|--limit ARG] [--server|PATH...] [-?|-h|--help]
Example: "$(basename "$1")" --author mike -r {2012-04-01:HEAD}
HELPTEXT
}

typeset authorArgs=
typeset isServerRevisions=

typeset -a allargs=()
while [ $# -gt 0 ]
do
    case "$1" in
	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
	--author)	shift; authorArgs=$1; shift;;
	--server)	shift; isServerRevisions='true';;
	*)
	    allargs+=("$1")
	    shift
	    ;;
    esac
done
if [ "$isServerRevisions" ]; then
    allargs+=($(svn-serverrevs))
fi

set -o pipefail
svn log --non-interactive --verbose "${allargs[@]}" | if [ "$authorArgs" ]; then
    awk -v authorExpr="$authorArgs" '
/^r[0-9]+ / {
    user = $3
}
/^Changed paths:/,/^$/ {
    if ($0 == "" || $0 ~ "^Changed paths:") {
	next
    }
    if (user ~ authorExpr) {
	print $0
    }
}
'
else
    sed -ne '
/^Changed paths:/,/^$/ {
    /^$/d
    /^Changed paths:/d
    p
}
'
fi | sort -k 2 -u | less --quit-on-intr --RAW-CONTROL-CHARS
