#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
Diff with predecessor, either current BASE revision to PREV, or
with -c REV revision REV to its predecessor. 
Note: The [@REV] is only a revision peg for use on the server; you cannot
specify a local revision with it. 
Usage: "$(basename "$1")" [-c|--change REV] [TARGET[@REV]...] [-?|-h|--help]
HELPTEXT
}

revisionRange='-r BASE:PREV'
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
    --change|-c)	shift; revisionRange="--change $1"; shift;;
esac

svn-diff $revisionRange "$@"
