#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
List revision number and author of the last commit.
Usage: "$(basename "$1")" [TARGET[@REV]...] [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

# Omit the file size and date; a plain 'll' tells this, too.
svn ls -v "$@" | cut -c 1-20,44-
