#!/bin/sh
# Allows svn-* scripts to invoke other svn-* scripts (or itself recursively :-)
# if they exist. This is necessary because the svn alias / svn() function from
# aliases.sh is not active inside a shell script. (And I also do not want other
# scripts to pick up my customized svn command, which would happen if I put a
# svn script into the PATH.)

printUsage()
{
    cat <<HELPTEXT
Internal helper script.
Usage: "$(basename "$1")" alias|command [ARGS...]
HELPTEXT
}

svnAlias="svn-$1"
if 'which' "$svnAlias" >/dev/null 2>&1; then
    shift
    "$svnAlias" "$@"
else
    'svn' "$@"
fi
