#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Cherry-pick some commit(s) and merge them into the current working copy.
Usage: "$(basename "$1")" [-c M[,N...] | -r N:M ...] [SOURCE[@REV]] [-?|-h|--help]
HELPTEXT
}

typeset -a allargs=()
typeset -a revisions=()
typeset -a changes=()
while [ $# -ne 0 ]
do
    case "$1" in
	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
	--change|-c)	shift; changes+=("$1"); shift;;
	--revision|-r)	shift; revisions+=("$1"); shift;;
	*)		allargs+=("$1")
			shift
			;;
    esac
done
if [ ${#allargs[@]} -eq 0 ]; then
    allargs=("$(svn-root)") || exit $?
fi

svn merge --no-ancestry ${revisions:+--revision} "${revisions[@]}" ${changes:+--change} "${changes[@]}" "${allargs[@]}"
svn-diff --stat "${allargs[@]}"
