#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
Undo "svn add PATH..."; unschedules the file from addition to Subversion, but
keeps the file in the working copy. 
Usage: "$(basename "$1")" [-?|-h|--help] PATH...
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

[ $# -gt 0 ] || { printUsage "$0"; exit 1; }

svn delete --keep-local "$@"
