#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Show the root dir of this working copy.
Usage: "$(basename "$1")" [-?|-h|--help] [PATH...]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

set -o pipefail
dirspec=$(cd "${1:-.}" && echo "$PWD")
if [ ! -d "${dirspec}/.svn" ]; then
    echo >&2 "Not inside a working copy${1:+: }${1:-.}"
    exit 1
fi

prevDirspec=
while [ "$prevDirspec" != "$dirspec" -a -d "${dirspec}/.svn" ]
do
    prevDirspec=$dirspec
    dirspec=$(dirname -- "$dirspec")
done
printf '%s\n' "$prevDirspec"
