#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
Show log message and textual diff for a particular commit. 
Usage: "$(basename "$1")" REV [-?|-h|--help]
HELPTEXT
}

case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac
[ $# -eq 0 ] && { echo >&2 "ERROR: Must specify REV."; printUsage "$0"; exit 1; }

(svn log --incremental -c "$@" && svn diff -c "$@") | less --RAW-CONTROL-CHARS
