#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
List the new path after file moves and renames and the corresponding revision.
--server	Instead of local history, only consider server revisions that
		you don't have yet.
--from		List the old path before the file move / rename in the revision
		instead.
--omit-revision	Omit the revision from the output; just print the changed paths.
Usage: "$(basename "$1")" [-r|--revision ARG] [-l|--limit ARG] [--from] [--omit-revision] [--server|PATH] [-?|-h|--help]
HELPTEXT
}

getRevisions()
{
    (eval "svn log --non-interactive --xml --with-no-revprops $revisionRangeArgs" '"${allargs[@]}"' || echo '</log>') | xmlstarlet sel --text -t -m '//logentry' -v '@revision' -n
    echo 'EOF'
}

getPath()
{
    repositoryUrl=$(svn-url "$@") || return $?
    printf %s "${repositoryUrl#"${repositoryRoot}"}"
}

printChangedPath()
{
    if [ "$isOmitRevision" ]; then
	printf '%s\n' "$2"
    else
	printf 'r%s\t%s\n' "$1" "$2"
    fi
}


revisionRangeArgs=
typeset isServerRevisions=
typeset -a serverArgs=
serverRevisionsArgs=
isFromPath=
isOmitRevision=
typeset -a allargs=()
while [ $# -gt 0 ]
do
    case "$1" in
	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
	-c|--change)	revisionRangeArgs="${revisionRangeArgs}${revisionRangeArgs:+ }$1 '$2'"; shift; shift;;
	-r|--revision)	revisionRangeArgs="${revisionRangeArgs}${revisionRangeArgs:+ }$1 '$2'"; shift; shift;;
	-l|--limit)	revisionRangeArgs="${revisionRangeArgs}${revisionRangeArgs:+ }$1 '$2'"; shift; shift;;
	--server)	shift; isServerRevisions='true';;
	--from)		shift; isFrom=t;;
	--omit-revision)
			shift; isOmitRevision=;;
	*)
	    if [ "$isServerRevisions" -a -d "$1" ]; then
		serverArgs=("$1")
	    else
		allargs+=("$1")
	    fi
	    shift
	    ;;
    esac
done
if [ "$isServerRevisions" ]; then
    serverRevisionsArgs=$(svn-serverrevs "${serverArgs[@]}")

    # Only add the revision filter for getRevisions() here, the server repo URL
    # must be passed to all svn commands.
    revisionRangeArgs="${revisionRangeArgs}${revisionRangeArgs:+ }${serverRevisionsArgs% *}"

    # Only append the server repo URL here; the revision selection is done by the loop.
    allargs+=("${serverRevisionsArgs##* }")
fi

set -o pipefail
repositoryRoot=$(svn info --non-interactive "${allargs[@]}" | sed -n -e 's/^Repository Root: \(.*\)$/\1/p') || exit $?
hasPathChanges=
getRevisions | while read revision
do
    if [ "$revision" = 'EOF' ]; then
	if [ "$hasPathChanges" ]; then
	    printChangedPath "$previousRevision" "$previousPath"
	fi
	break
    fi

    path=$(getPath --revision "$revision" "${allargs[@]}") || exit $?
    if [ "$previousPath" -a "$path" != "$previousPath" ]; then
	if [ "$isFrom" ]; then
	    printChangedPath "$previousRevision" "$path"
	else
	    hasPathChanges=t
	    printChangedPath "$previousRevision" "$previousPath"
	fi
    fi

    previousRevision=$revision
    previousPath=$path
done | less --quit-on-intr --RAW-CONTROL-CHARS
