#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Check out a working copy from a repository.
With -r REV, update the working copy to REV.
To specify a DATE:
    {2006-02-17}
    {15:30} or {15:30:00.200000}
    {"2006-02-17 15:30 +0230"}
    {2006-02-17T15:30Z}
    {20060217T1530-0500}
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[-r ARG1] URL[@REV]... [PATH] [-?|-h|--help]'
}

case "$1" in
    --help|-h|-\?)  shift; printUsage "$0"; exit 0;;
esac

if [ "$1" = '-r' ] && svn info --non-interactive >/dev/null 2>&1; then
    exec svn update "$@"
else
    exec svn checkout "$@"
fi
