#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Extract all Subversion revisions from stdin, and present them one per line.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[-?|-h|--help]'
}

case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

export GREP_OPTIONS=
grep --line-buffered -o -e '\(^\|[^[:alpha:]]\)r[[:digit:]]\+\([^[:alpha:]]\|$\)' | grep --line-buffered -o 'r[[:digit:]]\+'
