#!/bin/sh
## List all svn command extensions and newly defined commands. 

scriptDir=$(dirname -- "$0")
[ "$scriptDir" = "." ] && readonly scriptDir=$(dirname -- $(which -- "$0")) || readonly scriptDir=$(cd "$scriptDir" && echo "${PWD}") || { echo >&2 "ERROR: Cannot determine absolute script dirspec!"; exit 2; }
[ -d "$scriptDir" ] || { echo >&2 "ERROR: Cannot determine script directory!"; exit 2; }

for svnalias in "$scriptDir/"svn-*
do
    [ -x "$svnalias" ] || continue
    echo "[01m${svnalias##*svn-}[0m"
    sed -ne '/^## /s/^## /\t/p' "$svnalias"
done
