#!/bin/bash

readonly scriptDir=$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 2)
[ -d "$scriptDir" ] || { echo >&2 "ERROR: Cannot determine script directory!"; exit 2; }

wdiffCommand=dwdiff
type -t "$wdiffCommand" >/dev/null || wdiffCommand=wdiff
type -t "$wdiffCommand" >/dev/null || { echo >&2 "ERROR: dwdiff / wdiff tool not found"; exit 2; }

typeset -a colorMarkerArgs=(-w [41m -x [0m -y [42m -z [0m)
svnArgument=

# The wdiff tool does not support certain arguments that svn diff passes.
# Therefore, install this script as a wrapper, and filter out those arguments in
# stage 2.
if [ "${*/--stage2/}" = "$*" ]; then
    stageArgument=--stage2
    if [ "$1" = '--no-color' ]; then
	# The --no-color argument is handled by svn-diff itself, and not passed
	# on to the diff tool. Therefore, pass this information inside the
	# internal --stage2 argument.
	stageArgument=--stage2-no-color
	svnArgument=--no-color
	shift
    fi
    exec "$scriptDir/svn-diff" $svnArgument --diff-cmd "${BASH_SOURCE[0]}" -x "$stageArgument" "$@"
else
    typeset -a allargs=()
    while [ $# -gt 0 ]
    do
	case "$1" in
	    --stage2)		shift;;
	    --stage2-no-color)	shift
				colorMarkerArgs=()
				;;
	    -L)			shift; shift;;
	    -[cu])		shift;;
	    *)
		allargs+=("$1")
		shift
		;;
	esac
    done
    exec "$wdiffCommand" -P --no-common "${colorMarkerArgs[@]}" "${allargs[@]}"
fi
